### ISSUE TITLE
Add geolocation options

### ISSUE THREAD

**Issue by seansweeney** [cambridgegis/maplib#21]
We are starting to work on mobile versions of the embedded maps, which will be full-screen links from the “embedded” map page in the mobile city site.  One thing we’ll need to add for these is geolocation.  I think we’d want two options:

1. Automatically geolocate on load.
1. Geolocate button (probably under zoom buttons).

**Comment by sfarber** [comment]
Geolocation functionality has been added in commit cd4eeb0

Options added to maplib.config:
enableGeolocation: boolean
geolocateOnLoad: boolean

geolocateOnLoad requires enableGeolocation:true
